#!/usr/bin/env bash
set -Eeuo pipefail

# Generate a safe .env.local for CellFlow development/Testnet validation.
# Usage:
#   bash scripts/generate-env.sh
#   DATABASE_URL='postgresql://...' CKB_RPC_URL='https://...' bash scripts/generate-env.sh
#
# This script NEVER asks for or writes wallet/private keys.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${CELLFLOW_ENV_OUTPUT:-$ROOT/.env.local}"
EXAMPLE="$ROOT/.env.example"

[[ -f "$EXAMPLE" ]] || { echo "ERROR: missing $EXAMPLE" >&2; exit 1; }
command -v node >/dev/null 2>&1 || { echo "ERROR: Node.js 22+ is required" >&2; exit 1; }

NODE_MAJOR="$(node -p 'Number(process.versions.node.split(".")[0])')"
(( NODE_MAJOR >= 22 )) || { echo "ERROR: Node.js 22+ is required; found $(node -v)" >&2; exit 1; }

random_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "${1:-32}"
  else
    node -e "console.log(require('crypto').randomBytes(${1:-32}).toString('hex'))"
  fi
}

# Write one shell-sourceable + dotenv-compatible single-quoted value.
write_env() {
  local key="$1" value="${2-}" escaped
  escaped="$(printf '%s' "$value" | sed "s/'/'\"'\"'/g")"
  printf "%s='%s'\n" "$key" "$escaped" >> "$OUT"
}

DATABASE_URL="${DATABASE_URL:-postgresql://cellflow:cellflow_local_only@127.0.0.1:54329/cellflow}"
CKB_NETWORK="${CKB_NETWORK:-testnet}"
CKB_RPC_URL="${CKB_RPC_URL:-https://testnet.ckbapp.dev/rpc}"
CKB_RPC_FALLBACK_URL="${CKB_RPC_FALLBACK_URL:-}"
CKB_RPC_FALLBACK_URLS="${CKB_RPC_FALLBACK_URLS:-}"
CKB_EXPECTED_GENESIS_HASH="${CKB_EXPECTED_GENESIS_HASH:-}"

if [[ -z "$CKB_EXPECTED_GENESIS_HASH" ]] && command -v curl >/dev/null 2>&1; then
  # Best effort only; a disconnected machine can still generate the file and fill this later.
  GENESIS_JSON="$(curl -fsS --max-time 10 -H 'content-type: application/json' \
    -d '{"id":1,"jsonrpc":"2.0","method":"get_block_hash","params":["0x0"]}' \
    "$CKB_RPC_URL" 2>/dev/null || true)"
  if [[ -n "$GENESIS_JSON" ]]; then
    CKB_EXPECTED_GENESIS_HASH="$(printf '%s' "$GENESIS_JSON" | node -e '
      let s=""; process.stdin.on("data",d=>s+=d); process.stdin.on("end",()=>{
        try { const x=JSON.parse(s); if (typeof x.result === "string") process.stdout.write(x.result); } catch {}
      });
    ')"
  fi
fi

: > "$OUT"
chmod 600 "$OUT"
{
  echo "# Generated by scripts/generate-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# No wallet/private key belongs in this file."
} >> "$OUT"

write_env DATABASE_URL "$DATABASE_URL"
write_env CKB_NETWORK "$CKB_NETWORK"
write_env CKB_RPC_URL "$CKB_RPC_URL"
write_env CKB_RPC_FALLBACK_URL "$CKB_RPC_FALLBACK_URL"
write_env CKB_RPC_FALLBACK_URLS "$CKB_RPC_FALLBACK_URLS"
write_env CKB_EXPECTED_GENESIS_HASH "$CKB_EXPECTED_GENESIS_HASH"
write_env CKB_RPC_TIMEOUT_MS "${CKB_RPC_TIMEOUT_MS:-10000}"
write_env CKB_RPC_CIRCUIT_FAILURES "${CKB_RPC_CIRCUIT_FAILURES:-2}"
write_env CKB_RPC_CIRCUIT_COOLDOWN_MS "${CKB_RPC_CIRCUIT_COOLDOWN_MS:-30000}"
write_env CKB_ALLOW_INSECURE_RPC "${CKB_ALLOW_INSECURE_RPC:-false}"
write_env CELLFLOW_ENCRYPTION_KEY "${CELLFLOW_ENCRYPTION_KEY:-$(random_hex 32)}"
write_env CELLFLOW_BOOTSTRAP_TOKEN "${CELLFLOW_BOOTSTRAP_TOKEN:-$(random_hex 32)}"
write_env CRON_SECRET "${CRON_SECRET:-$(random_hex 32)}"
write_env CELLFLOW_SETUP_ENABLED "${CELLFLOW_SETUP_ENABLED:-true}"
write_env CELLFLOW_RELEASE_SHA "${CELLFLOW_RELEASE_SHA:-}"
write_env CELLFLOW_RECONCILE_CONCURRENCY "${CELLFLOW_RECONCILE_CONCURRENCY:-4}"
write_env CELLFLOW_WEBHOOK_CONCURRENCY "${CELLFLOW_WEBHOOK_CONCURRENCY:-6}"
write_env CELLFLOW_WEBHOOK_LEASE_SECONDS "${CELLFLOW_WEBHOOK_LEASE_SECONDS:-45}"
write_env CELLFLOW_WEBHOOK_MAX_ATTEMPTS "${CELLFLOW_WEBHOOK_MAX_ATTEMPTS:-8}"
write_env CELLFLOW_WEBHOOK_TIMEOUT_MS "${CELLFLOW_WEBHOOK_TIMEOUT_MS:-10000}"
write_env CELLFLOW_MAINTENANCE_RECONCILE_LIMIT "${CELLFLOW_MAINTENANCE_RECONCILE_LIMIT:-4}"
write_env CELLFLOW_MAINTENANCE_WEBHOOK_LIMIT "${CELLFLOW_MAINTENANCE_WEBHOOK_LIMIT:-12}"
write_env CELLFLOW_STALE_INTENT_MINUTES "${CELLFLOW_STALE_INTENT_MINUTES:-10}"
write_env CELLFLOW_RATE_LIMIT_PER_MINUTE "${CELLFLOW_RATE_LIMIT_PER_MINUTE:-240}"
write_env CELLFLOW_MAX_JSON_BODY_BYTES "${CELLFLOW_MAX_JSON_BODY_BYTES:-262144}"
write_env DEFAULT_CONFIRMATION_POLICY "${DEFAULT_CONFIRMATION_POLICY:-depth:4}"
write_env NEXT_PUBLIC_APP_URL "${NEXT_PUBLIC_APP_URL:-http://localhost:3000}"
write_env CELLFLOW_ENDPOINT "${CELLFLOW_ENDPOINT:-http://localhost:3000}"
write_env CELLFLOW_API_KEY "${CELLFLOW_API_KEY:-}"
write_env CELLFLOW_EVIDENCE_DIR "${CELLFLOW_EVIDENCE_DIR:-evidence/testnet/generated}"
write_env CELLFLOW_EVIDENCE_INTENT_ID "${CELLFLOW_EVIDENCE_INTENT_ID:-}"
write_env CELLFLOW_EVIDENCE_TX_HASH "${CELLFLOW_EVIDENCE_TX_HASH:-}"

cat <<MSG
Generated: $OUT

Next:
  set -a; source "$OUT"; set +a
  bash scripts/setup-local-postgres.sh   # optional if DATABASE_URL is not already usable
  npm run migrate
  npm run evidence:testnet-preflight

Important: keep signing keys in your wallet/test harness, never in CellFlow .env files.
MSG
